# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift-DocC

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: swift-actions/setup-swift@v1
    - name: Get swift version
      run: swift --version # Swift 5.8
    - uses: actions/checkout@v3
    - name: build docc
      run: |
        swift package --allow-writing-to-directory ../docs generate-documentation \
        --target ELSwift \
        --disable-indexing \
        --transform-for-static-hosting \
        --output-path ./docs
    - uses: actions/upload-pages-artifact@v1
      with:
        path: docs
